//! `morpholog generate views` end to end: the emitted SQL script, its
//! determinism (the read-side drift discipline is regenerate-and-diff,
//! exactly as for `python-client`), the committed golden, the model-hash
//! catalogue, base/derived separation, and the whole-run refusal
//! contract.

#![allow(clippy::unwrap_used, clippy::expect_used)]

mod common;
use common::{bin, repo_root};

use std::path::{Path, PathBuf};
use std::process::Command;

fn trade_lifecycle() -> PathBuf {
    repo_root().join("examples/10_trade_lifecycle/trade_lifecycle.morph")
}

fn golden() -> PathBuf {
    repo_root().join("examples/10_trade_lifecycle/trade_lifecycle_views.sql")
}

/// Run `generate views <file> [--schema S]`, returning the process output
/// (the SQL goes to stdout).
fn generate_stdout(file: &Path, schema: Option<&str>) -> std::process::Output {
    let mut args = vec![
        "generate".to_string(),
        "views".to_string(),
        file.to_str().unwrap().to_string(),
    ];
    if let Some(s) = schema {
        args.push("--schema".to_string());
        args.push(s.to_string());
    }
    Command::new(bin())
        .args(&args)
        .output()
        .expect("run morpholog generate views")
}

#[test]
fn generates_an_atomic_view_script_to_stdout() {
    let result = generate_stdout(&trade_lifecycle(), None);
    assert!(
        result.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&result.stderr)
    );
    let sql = String::from_utf8(result.stdout).unwrap();
    assert!(sql.starts_with("-- Generated by `morpholog generate views`"));
    assert!(sql.contains("BEGIN;"));
    assert!(sql.contains("CREATE SCHEMA IF NOT EXISTS \"morpholog_views\";"));
    assert!(sql.contains("CREATE OR REPLACE VIEW \"morpholog_views\".\"trade_settled\""));
    assert!(sql.contains("WITH governed_claims AS ("));
    assert!(sql.contains("CREATE OR REPLACE VIEW \"morpholog_views\".\"_morpholog_catalog\""));
    assert!(sql.trim_end().ends_with("COMMIT;"));
}

// A derived-claim head gets a view over the `morpholog_read` cache (one
// unified read surface), filtered by predicate and the generated model
// hash, and the catalogue records its kind. Base predicates still read
// `morpholog.claims`.
#[test]
fn derived_heads_get_a_derived_view_over_the_cache() {
    let result = generate_stdout(&trade_lifecycle(), None);
    let sql = String::from_utf8(result.stdout).unwrap();
    assert!(
        sql.contains("CREATE OR REPLACE VIEW \"morpholog_views\".\"trade_settled\""),
        "base view over claims"
    );
    assert!(
        sql.contains("CREATE OR REPLACE VIEW \"morpholog_views\".\"terms_timeline\""),
        "derived view present"
    );
    assert!(sql.contains("FROM morpholog_read.derived_claims c"));
    assert!(sql.contains("WHERE c.predicate_name = 'TermsTimeline'"));
    assert!(
        sql.contains("AND r.model_hash = "),
        "derived view filters by the generated model hash"
    );
    assert!(
        sql.contains("'terms_timeline', 'derived'"),
        "catalogue records the derived kind"
    );
    // The split is reported on stderr.
    let stderr = String::from_utf8(result.stderr).unwrap();
    assert!(
        stderr.contains("base") && stderr.contains("derived"),
        "got: {stderr}"
    );
}

// Determinism IS the drift contract: same binary and programme produce a
// byte-identical script, so an embedder's check is regenerate-and-diff.
#[test]
fn generation_is_byte_deterministic() {
    let a = generate_stdout(&trade_lifecycle(), None).stdout;
    let b = generate_stdout(&trade_lifecycle(), None).stdout;
    assert_eq!(a, b, "the script must be byte-identical across runs");
}

// The committed golden is the regenerate-and-diff anchor. If this fails,
// regenerate it with the command in the message.
#[test]
fn committed_golden_matches_fresh_generation() {
    let fresh = generate_stdout(&trade_lifecycle(), None).stdout;
    let committed = std::fs::read(golden()).unwrap();
    assert_eq!(
        committed, fresh,
        "examples/10_trade_lifecycle/trade_lifecycle_views.sql is stale; regenerate with:\n  \
         morpholog generate views examples/10_trade_lifecycle/trade_lifecycle.morph \
         --out examples/10_trade_lifecycle/trade_lifecycle_views.sql"
    );
}

// The catalogue carries the same model hash the generated Python client
// stamps, so SQL consumers and CI can pin to it.
#[test]
fn catalog_hash_matches_morpholog_hash() {
    let sql = String::from_utf8(generate_stdout(&trade_lifecycle(), None).stdout).unwrap();
    let hash_out = Command::new(bin())
        .args(["hash", trade_lifecycle().to_str().unwrap()])
        .output()
        .unwrap();
    let report: serde_json::Value = serde_json::from_slice(&hash_out.stdout).unwrap();
    let hash = report["hash"].as_str().unwrap();
    assert!(sql.contains(&format!("-- model hash: {hash}")));
    assert!(
        sql.contains(&format!("'{hash}'::text")),
        "the catalogue VALUES list carries the hash"
    );
}

#[test]
fn schema_flag_changes_the_qualifier() {
    let sql =
        String::from_utf8(generate_stdout(&trade_lifecycle(), Some("analytics")).stdout).unwrap();
    assert!(sql.contains("CREATE SCHEMA IF NOT EXISTS \"analytics\";"));
    assert!(sql.contains("CREATE OR REPLACE VIEW \"analytics\".\"trade_settled\""));
    assert!(!sql.contains("\"morpholog_views\""));
}

fn refusal_fixture(source: &str) -> (tempfile::TempDir, PathBuf) {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("model.morph");
    std::fs::write(&path, source).unwrap();
    (dir, path)
}

// Refusal is whole-run: a reserved-word field is named, and nothing is
// written to stdout.
#[test]
fn reserved_word_field_is_quoted_not_refused() {
    // A reserved-word field (`select`) is allowed: the generator quotes
    // every identifier, so the column is emitted as `AS "select"` rather
    // than refused. Consumers quote it in turn.
    let (_dir, path) = refusal_fixture(
        "program kw\n\
         predicate P(id: Subject, select: Decimal)\n\
         transformation t(id, select):\n    admit P(id, select)\n",
    );
    let result = generate_stdout(&path, None);
    assert!(
        result.status.success(),
        "a reserved-word field is quoted, not refused; stderr:\n{}",
        String::from_utf8_lossy(&result.stderr)
    );
    let sql = String::from_utf8_lossy(&result.stdout);
    assert!(
        sql.contains("AS \"select\""),
        "reserved-word column should be quoted: {sql}"
    );
}

#[test]
fn reserved_word_view_name_is_quoted_not_refused() {
    // The same policy applies to a generated view NAME: a predicate named
    // `Order` snakes to the reserved word `order`, and the view is quoted
    // rather than refused.
    let (_dir, path) = refusal_fixture(
        "program kwview\n\
         predicate Order(id: Subject)\n\
         transformation t(id):\n    admit Order(id)\n",
    );
    let result = generate_stdout(&path, None);
    assert!(
        result.status.success(),
        "a reserved-word view name is quoted, not refused; stderr:\n{}",
        String::from_utf8_lossy(&result.stderr)
    );
    let sql = String::from_utf8_lossy(&result.stdout);
    assert!(
        sql.contains("\"morpholog_views\".\"order\""),
        "reserved-word view name should be quoted: {sql}"
    );
}

// snake_case is many-to-one: `TradeID` and `Trade_id` are distinct lawful
// Morpholog names that render the same view.
#[test]
fn colliding_view_names_refuse_naming_both() {
    let (_dir, path) = refusal_fixture(
        "program coll\n\
         predicate TradeID(id: Subject)\n\
         predicate Trade_id(id: Subject)\n\
         transformation t(id):\n    admit TradeID(id)\n",
    );
    let result = generate_stdout(&path, None);
    assert!(!result.status.success());
    let stderr = String::from_utf8_lossy(&result.stderr);
    assert!(
        stderr.contains("all generate view `trade_id`"),
        "both sources collide on the generated view; got:\n{stderr}"
    );
}

#[test]
fn invalid_schema_refuses() {
    let result = generate_stdout(&trade_lifecycle(), Some("bad schema!"));
    assert!(!result.status.success());
    let stderr = String::from_utf8_lossy(&result.stderr);
    assert!(stderr.contains("--schema"), "got:\n{stderr}");
}
