[package]
name = "morpholog-test-support"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
morpholog-core = { path = "../morpholog-core" }
jiff = { workspace = true }
rust_decimal = { workspace = true }

[lints]
workspace = true
