//! Worked examples - the canonical Morpholog illustrations.
//!
//! The single authored form of each example is its surface-syntax
//! `.morph` file under `examples/<NN_dir>/<file>.morph`. `build.rs` reads
//! every one, extracts its `transformation` / `invariant` / `derived`
//! declarations, and generates the per-example accessor module (`program`,
//! `all_invariants`, one accessor per declaration) into `OUT_DIR`; the
//! `example_module!` calls below bring each in under its name, and the
//! `all_programs()` registry is generated the same way. So adding an example
//! is dropping a `.morph` plus one `example_module!(<name>)` line - no
//! accessor boilerplate and no list to maintain. That one line is the only
//! manual step, and it cannot be silently forgotten: the generated registry
//! references the module, so a missing line is a compile error, not a quietly
//! skipped example. The teaching surface and the runnable program cannot
//! drift. The few non-mechanical items a `.morph` cannot yield (domain
//! constants used by tests; accessors for generated discipline invariants)
//! are hand-written supplements in the `example_module!` bodies.
//!
//! **Not a stable API.** This crate is `pub` so tests and documentation
//! can share the canonical programs; it is not a user-facing API.

use morpholog_core::{Invariant, Program, Transformation};

/// Parse a built-in example's embedded `.morph` source into its
/// [`Program`]. A built-in example that fails to parse is a build-time
/// bug, so this panics rather than returning an error.
pub(crate) fn parse_example(name: &str, source: &str) -> Program {
    morpholog_surface::parse_program(source).unwrap_or_else(|diagnostics| {
        let rendered: String = diagnostics.iter().map(|d| d.render(name, source)).collect();
        panic!("built-in example `{name}` must parse:\n{rendered}")
    })
}

/// Clone a named invariant out of a parsed example program. A missing
/// name is a bug in the accessor, not a runtime condition.
pub(crate) fn invariant(program: &Program, name: &str) -> Invariant {
    program
        .invariant(name)
        .unwrap_or_else(|| panic!("example invariant `{name}` not found"))
        .clone()
}

/// Clone a named transformation out of a parsed example program.
pub(crate) fn transformation(program: &Program, name: &str) -> Transformation {
    program
        .transformation(name)
        .unwrap_or_else(|| panic!("example transformation `{name}` not found"))
        .clone()
}

/// Clone a derived claim (by its output predicate name) out of a parsed
/// example program.
pub(crate) fn derived(program: &Program, predicate: &str) -> morpholog_core::DerivedClaim {
    program
        .derived_claim(predicate)
        .unwrap_or_else(|| panic!("example derived claim `{predicate}` not found"))
        .clone()
}

/// Each example's accessor module is generated by `build.rs` from its
/// `.morph` and lives in `OUT_DIR`; this brings it in under its name. The
/// optional `{ ... }` body is a hand-written supplement for the few
/// non-mechanical items a `.morph` cannot yield: domain-symbol constants
/// used by tests, and accessors for generated discipline invariants (whose
/// names exist only after parse-time lowering, not in the source).
macro_rules! example_module {
    ($name:ident) => {
        pub mod $name {
            include!(concat!(env!("OUT_DIR"), "/", stringify!($name), ".rs"));
        }
    };
    ($name:ident { $($supplement:tt)* }) => {
        pub mod $name {
            include!(concat!(env!("OUT_DIR"), "/", stringify!($name), ".rs"));
            $($supplement)*
        }
    };
}

example_module!(approval_controls);
example_module!(biometric_identification_oversight);
example_module!(borrowing_base);
example_module!(carbon_credit_provenance {
    pub fn issued_unique_by_measurement() -> Invariant {
        crate::invariant(&PROGRAM, "issued_unique_by_measurement")
    }
});
example_module!(chess_transition_invariants);
example_module!(clinical_trial_enrolment {
    pub const ROLE_RANDOMISE_PARTICIPANT: &str = "randomise_participant";
});
example_module!(double_entry_ledger);
example_module!(insurance_claim_settlement);
example_module!(kyc_sanctions_screening {
    pub const SANCTIONS: &str = "sanctions";
    pub const PEP: &str = "pep";
    pub const DISP_CLEAN: &str = "clean";
    pub const DISP_MATCH: &str = "match";
    pub const DISP_ADJUDICATED_CLEAR: &str = "adjudicated_clear";
});
example_module!(laytime_demurrage);
example_module!(margin_call_run);
example_module!(settlement_netting);
example_module!(trade_lifecycle);
example_module!(verified_revenue {
    pub const BANK_DEBT_SERVICE: &str = "bank_debt_service";
    pub const INVESTOR_REPORTING: &str = "investor_reporting";
});

// The auto-discovered `all_programs()` registry (generated by build.rs).
include!(concat!(env!("OUT_DIR"), "/_registry.rs"));
