//! Worked examples - the canonical Morpholog illustrations.
//!
//! Each example is authored once, as `examples/<NN_dir>/<file>.morph`.
//! `build.rs` generates an accessor module for each (`program`,
//! `all_invariants`, one accessor per declaration) plus the `all_programs()`
//! registry. Adding an example means adding a `.morph` and one
//! `example_module!(<name>)` line below; forgetting the line is a compile
//! error. Because tests run the same source readers learn from, the two
//! cannot drift.
//!
//! **Not a stable API.** This crate is `pub` so tests and documentation
//! can share the canonical programs; it is not a user-facing API.

use morpholog_core::{Invariant, Program, Transformation};

/// Parse a built-in example's embedded `.morph` source into its [`Program`].
/// Panics on failure: a built-in example that does not parse is a bug.
pub(crate) fn parse_example(name: &str, source: &str) -> Program {
    morpholog_surface::parse_program(source).unwrap_or_else(|diagnostics| {
        let rendered: String = diagnostics.iter().map(|d| d.render(name, source)).collect();
        panic!("built-in example `{name}` must parse:\n{rendered}")
    })
}

/// Clone a named invariant out of a parsed example program. A missing
/// name is a bug in the accessor, not a runtime condition.
pub(crate) fn invariant(program: &Program, name: &str) -> Invariant {
    program
        .invariant(name)
        .unwrap_or_else(|| panic!("example invariant `{name}` not found"))
        .clone()
}

/// Clone a named transformation out of a parsed example program.
pub(crate) fn transformation(program: &Program, name: &str) -> Transformation {
    program
        .transformation(name)
        .unwrap_or_else(|| panic!("example transformation `{name}` not found"))
        .clone()
}

/// Clone a derived claim (by its output predicate name) out of a parsed
/// example program.
pub(crate) fn derived(program: &Program, predicate: &str) -> morpholog_core::DerivedClaim {
    program
        .derived_claim(predicate)
        .unwrap_or_else(|| panic!("example derived claim `{predicate}` not found"))
        .clone()
}

/// Brings in an example's generated accessor module under its name. The
/// optional `{ ... }` body adds what the `.morph` scan cannot yield: domain
/// constants used by tests, and accessors for generated discipline invariants
/// (their names exist only after parsing).
macro_rules! example_module {
    ($name:ident) => {
        pub mod $name {
            include!(concat!(env!("OUT_DIR"), "/", stringify!($name), ".rs"));
        }
    };
    ($name:ident { $($supplement:tt)* }) => {
        pub mod $name {
            include!(concat!(env!("OUT_DIR"), "/", stringify!($name), ".rs"));
            $($supplement)*
        }
    };
}

example_module!(approval_controls);
example_module!(biometric_identification_oversight);
example_module!(borrowing_base);
example_module!(carbon_credit_provenance {
    pub fn issued_unique_by_measurement() -> Invariant {
        crate::invariant(&PROGRAM, "issued_unique_by_measurement")
    }
});
example_module!(charging_years);
example_module!(chess_transition_invariants);
example_module!(clinical_trial_enrolment {
    pub const ROLE_RANDOMISE_PARTICIPANT: &str = "randomise_participant";
});
example_module!(covenant_reporting);
example_module!(double_entry_ledger);
example_module!(insurance_claim_settlement);
example_module!(kyc_sanctions_screening {
    pub const SANCTIONS: &str = "sanctions";
    pub const PEP: &str = "pep";
    pub const DISP_CLEAN: &str = "clean";
    pub const DISP_MATCH: &str = "match";
    pub const DISP_ADJUDICATED_CLEAR: &str = "adjudicated_clear";
});
example_module!(laytime_demurrage);
example_module!(margin_call_run);
example_module!(metered_billing);
example_module!(operational_information);
example_module!(release_governance);
example_module!(scoped_charges);
example_module!(settlement_netting);
example_module!(trade_lifecycle);
example_module!(verified_revenue {
    pub const BANK_DEBT_SERVICE: &str = "bank_debt_service";
    pub const INVESTOR_REPORTING: &str = "investor_reporting";
});

/// One worked example as build discovery found it. The generated
/// [`all_examples`] registry is the one list of worked examples:
/// `all_programs()` derives from it, and callers that need the file
/// rather than the programme iterate it instead of walking the filesystem.
#[derive(Debug, Clone)]
pub struct ExampleDescriptor {
    /// The accessor module's name (`double_entry_ledger`).
    pub name: &'static str,
    /// The `.morph` path relative to the repo's `examples/` directory
    /// (`03_double_entry_ledger/ledger.morph`).
    pub rel_path: &'static str,
    /// The `.morph` source, embedded at compile time.
    pub source: &'static str,
    /// The module's cached programme accessor.
    pub program: fn() -> morpholog_core::Program,
}

// Generated by build.rs: `all_examples()` and `all_programs()`.
include!(concat!(env!("OUT_DIR"), "/_registry.rs"));
