-- Generated by `morpholog generate views` - do not edit.
-- programme: trade_lifecycle
-- model hash: sha256:99e750741460f0f14be19d791636476b2d8c1b1eeb87a2a01a4dccd634a5cee2

BEGIN;

CREATE SCHEMA IF NOT EXISTS "morpholog_views";

-- View for base predicate `TradeCaptured`.
CREATE OR REPLACE VIEW "morpholog_views"."trade_captured" AS
WITH governed_claims AS (
    SELECT arguments, asserted_in, asserted_at
    FROM morpholog.claims
    WHERE predicate_name = 'TradeCaptured'
)
SELECT
    asserted_in                AS "_morpholog_asserted_in",
    asserted_at                AS "_morpholog_asserted_at",
    arguments                  AS "_morpholog_arguments",
    arguments -> 0 ->> 'value' AS "trade",
    arguments -> 1 ->> 'value' AS "commodity",
    arguments -> 2 ->> 'value' AS "direction"
FROM governed_claims;
COMMENT ON VIEW "morpholog_views"."trade_captured" IS 'Generated by Morpholog; predicate=TradeCaptured';
COMMENT ON COLUMN "morpholog_views"."trade_captured"."trade" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."trade_captured"."commodity" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."trade_captured"."direction" IS 'Morpholog kind Subject';

-- View for base predicate `TradeTerms`.
CREATE OR REPLACE VIEW "morpholog_views"."trade_terms" AS
WITH governed_claims AS (
    SELECT arguments, asserted_in, asserted_at
    FROM morpholog.claims
    WHERE predicate_name = 'TradeTerms'
)
SELECT
    asserted_in                           AS "_morpholog_asserted_in",
    asserted_at                           AS "_morpholog_asserted_at",
    arguments                             AS "_morpholog_arguments",
    arguments -> 0 ->> 'value'            AS "trade",
    arguments -> 1 ->> 'value'            AS "version_id",
    (arguments -> 2 ->> 'value')::numeric AS "quantity",
    arguments -> 3 ->> 'value'            AS "delivery_period",
    (arguments -> 4 ->> 'value')::date    AS "effective_from"
FROM governed_claims;
COMMENT ON VIEW "morpholog_views"."trade_terms" IS 'Generated by Morpholog; predicate=TradeTerms';
COMMENT ON COLUMN "morpholog_views"."trade_terms"."trade" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."trade_terms"."version_id" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."trade_terms"."quantity" IS 'Morpholog kind Decimal';
COMMENT ON COLUMN "morpholog_views"."trade_terms"."delivery_period" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."trade_terms"."effective_from" IS 'Morpholog kind Date';

-- View for base predicate `TradeTermsSupersedes`.
CREATE OR REPLACE VIEW "morpholog_views"."trade_terms_supersedes" AS
WITH governed_claims AS (
    SELECT arguments, asserted_in, asserted_at
    FROM morpholog.claims
    WHERE predicate_name = 'TradeTermsSupersedes'
)
SELECT
    asserted_in                AS "_morpholog_asserted_in",
    asserted_at                AS "_morpholog_asserted_at",
    arguments                  AS "_morpholog_arguments",
    arguments -> 0 ->> 'value' AS "new_version_id",
    arguments -> 1 ->> 'value' AS "prior_version_id"
FROM governed_claims;
COMMENT ON VIEW "morpholog_views"."trade_terms_supersedes" IS 'Generated by Morpholog; predicate=TradeTermsSupersedes';
COMMENT ON COLUMN "morpholog_views"."trade_terms_supersedes"."new_version_id" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."trade_terms_supersedes"."prior_version_id" IS 'Morpholog kind Subject';

-- View for base predicate `CapturedPrice`.
CREATE OR REPLACE VIEW "morpholog_views"."captured_price" AS
WITH governed_claims AS (
    SELECT arguments, asserted_in, asserted_at
    FROM morpholog.claims
    WHERE predicate_name = 'CapturedPrice'
)
SELECT
    asserted_in                           AS "_morpholog_asserted_in",
    asserted_at                           AS "_morpholog_asserted_at",
    arguments                             AS "_morpholog_arguments",
    arguments -> 0 ->> 'value'            AS "trade",
    (arguments -> 1 ->> 'value')::numeric AS "price"
FROM governed_claims;
COMMENT ON VIEW "morpholog_views"."captured_price" IS 'Generated by Morpholog; predicate=CapturedPrice';
COMMENT ON COLUMN "morpholog_views"."captured_price"."trade" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."captured_price"."price" IS 'Morpholog kind Decimal';

-- View for base predicate `MayConfirm`.
CREATE OR REPLACE VIEW "morpholog_views"."may_confirm" AS
WITH governed_claims AS (
    SELECT arguments, asserted_in, asserted_at
    FROM morpholog.claims
    WHERE predicate_name = 'MayConfirm'
)
SELECT
    asserted_in                AS "_morpholog_asserted_in",
    asserted_at                AS "_morpholog_asserted_at",
    arguments                  AS "_morpholog_arguments",
    arguments -> 0 ->> 'value' AS "principal",
    arguments -> 1 ->> 'value' AS "commodity"
FROM governed_claims;
COMMENT ON VIEW "morpholog_views"."may_confirm" IS 'Generated by Morpholog; predicate=MayConfirm';
COMMENT ON COLUMN "morpholog_views"."may_confirm"."principal" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."may_confirm"."commodity" IS 'Morpholog kind Subject';

-- View for base predicate `TradeConfirmed`.
CREATE OR REPLACE VIEW "morpholog_views"."trade_confirmed" AS
WITH governed_claims AS (
    SELECT arguments, asserted_in, asserted_at
    FROM morpholog.claims
    WHERE predicate_name = 'TradeConfirmed'
)
SELECT
    asserted_in                AS "_morpholog_asserted_in",
    asserted_at                AS "_morpholog_asserted_at",
    arguments                  AS "_morpholog_arguments",
    arguments -> 0 ->> 'value' AS "trade",
    arguments -> 1 ->> 'value' AS "counterparty",
    arguments -> 2 ->> 'value' AS "confirmation_id",
    arguments -> 3 ->> 'value' AS "confirmed_by"
FROM governed_claims;
COMMENT ON VIEW "morpholog_views"."trade_confirmed" IS 'Generated by Morpholog; predicate=TradeConfirmed';
COMMENT ON COLUMN "morpholog_views"."trade_confirmed"."trade" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."trade_confirmed"."counterparty" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."trade_confirmed"."confirmation_id" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."trade_confirmed"."confirmed_by" IS 'Morpholog kind Subject';

-- View for base predicate `OfficialPrice`.
CREATE OR REPLACE VIEW "morpholog_views"."official_price" AS
WITH governed_claims AS (
    SELECT arguments, asserted_in, asserted_at
    FROM morpholog.claims
    WHERE predicate_name = 'OfficialPrice'
)
SELECT
    asserted_in                           AS "_morpholog_asserted_in",
    asserted_at                           AS "_morpholog_asserted_at",
    arguments                             AS "_morpholog_arguments",
    arguments -> 0 ->> 'value'            AS "trade",
    (arguments -> 1 ->> 'value')::numeric AS "price",
    arguments -> 2 ->> 'value'            AS "official_price_id"
FROM governed_claims;
COMMENT ON VIEW "morpholog_views"."official_price" IS 'Generated by Morpholog; predicate=OfficialPrice';
COMMENT ON COLUMN "morpholog_views"."official_price"."trade" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."official_price"."price" IS 'Morpholog kind Decimal';
COMMENT ON COLUMN "morpholog_views"."official_price"."official_price_id" IS 'Morpholog kind Subject';

-- View for base predicate `CurrentOfficialPrice`.
CREATE OR REPLACE VIEW "morpholog_views"."current_official_price" AS
WITH governed_claims AS (
    SELECT arguments, asserted_in, asserted_at
    FROM morpholog.claims
    WHERE predicate_name = 'CurrentOfficialPrice'
)
SELECT
    asserted_in                AS "_morpholog_asserted_in",
    asserted_at                AS "_morpholog_asserted_at",
    arguments                  AS "_morpholog_arguments",
    arguments -> 0 ->> 'value' AS "trade",
    arguments -> 1 ->> 'value' AS "official_price_id"
FROM governed_claims;
COMMENT ON VIEW "morpholog_views"."current_official_price" IS 'Generated by Morpholog; predicate=CurrentOfficialPrice';
COMMENT ON COLUMN "morpholog_views"."current_official_price"."trade" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."current_official_price"."official_price_id" IS 'Morpholog kind Subject';

-- View for base predicate `OfficialPriceSupersedes`.
CREATE OR REPLACE VIEW "morpholog_views"."official_price_supersedes" AS
WITH governed_claims AS (
    SELECT arguments, asserted_in, asserted_at
    FROM morpholog.claims
    WHERE predicate_name = 'OfficialPriceSupersedes'
)
SELECT
    asserted_in                AS "_morpholog_asserted_in",
    asserted_at                AS "_morpholog_asserted_at",
    arguments                  AS "_morpholog_arguments",
    arguments -> 0 ->> 'value' AS "new_official_price_id",
    arguments -> 1 ->> 'value' AS "prior_official_price_id"
FROM governed_claims;
COMMENT ON VIEW "morpholog_views"."official_price_supersedes" IS 'Generated by Morpholog; predicate=OfficialPriceSupersedes';
COMMENT ON COLUMN "morpholog_views"."official_price_supersedes"."new_official_price_id" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."official_price_supersedes"."prior_official_price_id" IS 'Morpholog kind Subject';

-- View for base predicate `TradeSettled`.
CREATE OR REPLACE VIEW "morpholog_views"."trade_settled" AS
WITH governed_claims AS (
    SELECT arguments, asserted_in, asserted_at
    FROM morpholog.claims
    WHERE predicate_name = 'TradeSettled'
)
SELECT
    asserted_in                           AS "_morpholog_asserted_in",
    asserted_at                           AS "_morpholog_asserted_at",
    arguments                             AS "_morpholog_arguments",
    arguments -> 0 ->> 'value'            AS "trade",
    (arguments -> 1 ->> 'value')::numeric AS "settled_qty",
    arguments -> 2 ->> 'value'            AS "settlement_id",
    arguments -> 3 ->> 'value'            AS "official_price_id",
    (arguments -> 4 ->> 'value')::date    AS "effective_on"
FROM governed_claims;
COMMENT ON VIEW "morpholog_views"."trade_settled" IS 'Generated by Morpholog; predicate=TradeSettled';
COMMENT ON COLUMN "morpholog_views"."trade_settled"."trade" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."trade_settled"."settled_qty" IS 'Morpholog kind Decimal';
COMMENT ON COLUMN "morpholog_views"."trade_settled"."settlement_id" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."trade_settled"."official_price_id" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."trade_settled"."effective_on" IS 'Morpholog kind Date';

-- View for derived predicate `TermsTimeline`.
CREATE OR REPLACE VIEW "morpholog_views"."terms_timeline" AS
WITH governed_derived AS (
    SELECT c.arguments, r.refreshed_at, r.model_hash,
           r.source_snapshot_transition_id, r.source_snapshot_committed_at
    FROM morpholog_read.derived_claims c
    JOIN morpholog_read.derived_active a ON c.refresh_id = a.refresh_id
    JOIN morpholog_read.derived_refreshes r ON r.refresh_id = a.refresh_id
    WHERE c.predicate_name = 'TermsTimeline'
      AND r.model_hash = 'sha256:99e750741460f0f14be19d791636476b2d8c1b1eeb87a2a01a4dccd634a5cee2'
)
SELECT
    refreshed_at                          AS "_morpholog_refreshed_at",
    model_hash                            AS "_morpholog_model_hash",
    source_snapshot_transition_id         AS "_morpholog_source_snapshot_transition_id",
    source_snapshot_committed_at          AS "_morpholog_source_snapshot_committed_at",
    arguments                             AS "_morpholog_arguments",
    arguments -> 0 ->> 'value'            AS "trade",
    arguments -> 1 ->> 'value'            AS "version_id",
    arguments -> 2 ->> 'value'            AS "delivery_period",
    (arguments -> 3 ->> 'value')::date    AS "effective_from",
    (arguments -> 4 ->> 'value')::numeric AS "quantity"
FROM governed_derived;
COMMENT ON VIEW "morpholog_views"."terms_timeline" IS 'Generated by Morpholog; derived predicate=TermsTimeline; populated by `morpholog refresh derived`; empty until a refresh for this model hash';
COMMENT ON COLUMN "morpholog_views"."terms_timeline"."trade" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."terms_timeline"."version_id" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."terms_timeline"."delivery_period" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."terms_timeline"."effective_from" IS 'Morpholog kind Date';
COMMENT ON COLUMN "morpholog_views"."terms_timeline"."quantity" IS 'Morpholog kind Decimal';

-- Model catalogue: the programme, its model hash, and the views generated.
CREATE OR REPLACE VIEW "morpholog_views"."_morpholog_catalog" AS
SELECT * FROM ( VALUES
    ('trade_lifecycle'::text, 'sha256:99e750741460f0f14be19d791636476b2d8c1b1eeb87a2a01a4dccd634a5cee2'::text, 'TradeCaptured'::text, 'trade_captured'::text, 'base'::text),
    ('trade_lifecycle', 'sha256:99e750741460f0f14be19d791636476b2d8c1b1eeb87a2a01a4dccd634a5cee2', 'TradeTerms', 'trade_terms', 'base'),
    ('trade_lifecycle', 'sha256:99e750741460f0f14be19d791636476b2d8c1b1eeb87a2a01a4dccd634a5cee2', 'TradeTermsSupersedes', 'trade_terms_supersedes', 'base'),
    ('trade_lifecycle', 'sha256:99e750741460f0f14be19d791636476b2d8c1b1eeb87a2a01a4dccd634a5cee2', 'CapturedPrice', 'captured_price', 'base'),
    ('trade_lifecycle', 'sha256:99e750741460f0f14be19d791636476b2d8c1b1eeb87a2a01a4dccd634a5cee2', 'MayConfirm', 'may_confirm', 'base'),
    ('trade_lifecycle', 'sha256:99e750741460f0f14be19d791636476b2d8c1b1eeb87a2a01a4dccd634a5cee2', 'TradeConfirmed', 'trade_confirmed', 'base'),
    ('trade_lifecycle', 'sha256:99e750741460f0f14be19d791636476b2d8c1b1eeb87a2a01a4dccd634a5cee2', 'OfficialPrice', 'official_price', 'base'),
    ('trade_lifecycle', 'sha256:99e750741460f0f14be19d791636476b2d8c1b1eeb87a2a01a4dccd634a5cee2', 'CurrentOfficialPrice', 'current_official_price', 'base'),
    ('trade_lifecycle', 'sha256:99e750741460f0f14be19d791636476b2d8c1b1eeb87a2a01a4dccd634a5cee2', 'OfficialPriceSupersedes', 'official_price_supersedes', 'base'),
    ('trade_lifecycle', 'sha256:99e750741460f0f14be19d791636476b2d8c1b1eeb87a2a01a4dccd634a5cee2', 'TradeSettled', 'trade_settled', 'base'),
    ('trade_lifecycle', 'sha256:99e750741460f0f14be19d791636476b2d8c1b1eeb87a2a01a4dccd634a5cee2', 'TermsTimeline', 'terms_timeline', 'derived')
) AS generated(programme_name, model_hash, predicate_name, view_name, kind);
COMMENT ON VIEW "morpholog_views"."_morpholog_catalog" IS 'Generated by Morpholog; the model catalogue for this view surface';

COMMIT;
