[package]
name = "morpholog-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "morpholog"
path = "src/main.rs"

[dependencies]
morpholog-postgres = { path = "../morpholog-postgres" }
clap = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
