"""A typed Morpholog client for programme `trade_lifecycle`.

GENERATED by `morpholog generate python-client` - do not edit;
regenerate when the programme changes. The model hash in
`__init__.py` names the rules this client was built against.
"""

import sys

if sys.version_info < (3, 10):
    raise RuntimeError(
        f"morpholog_client requires Python 3.10+ "
        f"(running {sys.version_info.major}.{sys.version_info.minor}); "
        f"the generated code holds a conservative floor on purpose"
    )

PROGRAM = "trade_lifecycle"
MODEL_HASH = "sha256:c3571c9f7c0ac2bee44ec10fe8c119d4ffee093438072d92d64d2cd4e70608a3"
MORPHOLOG_VERSION = "0.0.4"
PYTHON_FLOOR = (3, 10)

from . import envelopes, models, values  # noqa: E402
from .adapter import Morpholog, MorphologError  # noqa: E402

__all__ = [
    "PROGRAM",
    "MODEL_HASH",
    "MORPHOLOG_VERSION",
    "PYTHON_FLOOR",
    "Morpholog",
    "MorphologError",
    "envelopes",
    "models",
    "values",
]
