"""Typed request, read, and payload models for programme `trade_lifecycle`.

GENERATED by `morpholog generate python-client` - do not edit;
regenerate when the programme changes. The model hash in
`__init__.py` names the rules this client was built against.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal
from typing import ClassVar

from . import values


@dataclass(frozen=True)
class CaptureTradeRequest:
    """Arguments for `capture_trade`."""

    TRANSFORMATION: ClassVar[str] = "capture_trade"

    trade: str
    commodity: str
    direction: str
    version_id: str
    quantity: Decimal
    delivery_period: str
    captured_on: date
    price: Decimal

    def to_args_named(self) -> dict[str, object]:
        return {
            "trade": values.encode_named(self.trade),
            "commodity": values.encode_named(self.commodity),
            "direction": values.encode_named(self.direction),
            "version_id": values.encode_named(self.version_id),
            "quantity": values.encode_named(self.quantity),
            "delivery_period": values.encode_named(self.delivery_period),
            "captured_on": values.encode_named(self.captured_on),
            "price": values.encode_named(self.price),
        }


@dataclass(frozen=True)
class AmendTradeTermsRequest:
    """Arguments for `amend_trade_terms`."""

    TRANSFORMATION: ClassVar[str] = "amend_trade_terms"

    trade: str
    prior_version_id: str
    new_version_id: str
    quantity: Decimal
    delivery_period: str
    effective_from: date

    def to_args_named(self) -> dict[str, object]:
        return {
            "trade": values.encode_named(self.trade),
            "prior_version_id": values.encode_named(self.prior_version_id),
            "new_version_id": values.encode_named(self.new_version_id),
            "quantity": values.encode_named(self.quantity),
            "delivery_period": values.encode_named(self.delivery_period),
            "effective_from": values.encode_named(self.effective_from),
        }


@dataclass(frozen=True)
class GrantConfirmAuthorityRequest:
    """Arguments for `grant_confirm_authority`."""

    TRANSFORMATION: ClassVar[str] = "grant_confirm_authority"

    principal: str
    commodity: str

    def to_args_named(self) -> dict[str, object]:
        return {
            "principal": values.encode_named(self.principal),
            "commodity": values.encode_named(self.commodity),
        }


@dataclass(frozen=True)
class SetPositionLimitRequest:
    """Arguments for `set_position_limit`."""

    TRANSFORMATION: ClassVar[str] = "set_position_limit"

    commodity: str
    limit: Decimal

    def to_args_named(self) -> dict[str, object]:
        return {
            "commodity": values.encode_named(self.commodity),
            "limit": values.encode_named(self.limit),
        }


@dataclass(frozen=True)
class ConfirmTradeRequest:
    """Arguments for `confirm_trade`."""

    TRANSFORMATION: ClassVar[str] = "confirm_trade"

    trade: str
    counterparty: str
    confirmation_id: str
    official_price_id: str
    confirmed_price: Decimal

    def to_args_named(self) -> dict[str, object]:
        return {
            "trade": values.encode_named(self.trade),
            "counterparty": values.encode_named(self.counterparty),
            "confirmation_id": values.encode_named(self.confirmation_id),
            "official_price_id": values.encode_named(self.official_price_id),
            "confirmed_price": values.encode_named(self.confirmed_price),
        }


@dataclass(frozen=True)
class CorrectOfficialPriceRequest:
    """Arguments for `correct_official_price`."""

    TRANSFORMATION: ClassVar[str] = "correct_official_price"

    trade: str
    prior_official_price_id: str
    new_official_price_id: str
    corrected_price: Decimal

    def to_args_named(self) -> dict[str, object]:
        return {
            "trade": values.encode_named(self.trade),
            "prior_official_price_id": values.encode_named(self.prior_official_price_id),
            "new_official_price_id": values.encode_named(self.new_official_price_id),
            "corrected_price": values.encode_named(self.corrected_price),
        }


@dataclass(frozen=True)
class SettleTradeRequest:
    """Arguments for `settle_trade`."""

    TRANSFORMATION: ClassVar[str] = "settle_trade"

    trade: str
    settled_qty: Decimal
    settlement_id: str
    official_price_id: str
    effective_on: date

    def to_args_named(self) -> dict[str, object]:
        return {
            "trade": values.encode_named(self.trade),
            "settled_qty": values.encode_named(self.settled_qty),
            "settlement_id": values.encode_named(self.settlement_id),
            "official_price_id": values.encode_named(self.official_price_id),
            "effective_on": values.encode_named(self.effective_on),
        }


@dataclass(frozen=True)
class TradeCapturedClaim:
    """One admitted `TradeCaptured` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "TradeCaptured"

    trade: str
    commodity: str
    direction: str

    @classmethod
    def from_named(cls, args: dict[str, object]) -> TradeCapturedClaim:
        raw = args["trade"]
        trade = raw
        raw = args["commodity"]
        commodity = raw
        raw = args["direction"]
        direction = raw
        return cls(trade=trade, commodity=commodity, direction=direction)


@dataclass(frozen=True)
class TradeTermsClaim:
    """One admitted `TradeTerms` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "TradeTerms"

    trade: str
    version_id: str
    quantity: Decimal
    delivery_period: str
    effective_from: date

    @classmethod
    def from_named(cls, args: dict[str, object]) -> TradeTermsClaim:
        raw = args["trade"]
        trade = raw
        raw = args["version_id"]
        version_id = raw
        raw = args["quantity"]
        quantity = values.parse_decimal(raw)
        raw = args["delivery_period"]
        delivery_period = raw
        raw = args["effective_from"]
        effective_from = values.parse_date(raw)
        return cls(trade=trade, version_id=version_id, quantity=quantity, delivery_period=delivery_period, effective_from=effective_from)


@dataclass(frozen=True)
class TradeTermsSupersedesClaim:
    """One admitted `TradeTermsSupersedes` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "TradeTermsSupersedes"

    new_version_id: str
    prior_version_id: str

    @classmethod
    def from_named(cls, args: dict[str, object]) -> TradeTermsSupersedesClaim:
        raw = args["new_version_id"]
        new_version_id = raw
        raw = args["prior_version_id"]
        prior_version_id = raw
        return cls(new_version_id=new_version_id, prior_version_id=prior_version_id)


@dataclass(frozen=True)
class CapturedPriceClaim:
    """One admitted `CapturedPrice` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "CapturedPrice"

    trade: str
    price: Decimal

    @classmethod
    def from_named(cls, args: dict[str, object]) -> CapturedPriceClaim:
        raw = args["trade"]
        trade = raw
        raw = args["price"]
        price = values.parse_decimal(raw)
        return cls(trade=trade, price=price)


@dataclass(frozen=True)
class MayConfirmClaim:
    """One admitted `MayConfirm` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "MayConfirm"

    principal: str
    commodity: str

    @classmethod
    def from_named(cls, args: dict[str, object]) -> MayConfirmClaim:
        raw = args["principal"]
        principal = raw
        raw = args["commodity"]
        commodity = raw
        return cls(principal=principal, commodity=commodity)


@dataclass(frozen=True)
class TradeConfirmedClaim:
    """One admitted `TradeConfirmed` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "TradeConfirmed"

    trade: str
    counterparty: str
    confirmation_id: str
    confirmed_by: str

    @classmethod
    def from_named(cls, args: dict[str, object]) -> TradeConfirmedClaim:
        raw = args["trade"]
        trade = raw
        raw = args["counterparty"]
        counterparty = raw
        raw = args["confirmation_id"]
        confirmation_id = raw
        raw = args["confirmed_by"]
        confirmed_by = raw
        return cls(trade=trade, counterparty=counterparty, confirmation_id=confirmation_id, confirmed_by=confirmed_by)


@dataclass(frozen=True)
class OfficialPriceClaim:
    """One admitted `OfficialPrice` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "OfficialPrice"

    trade: str
    price: Decimal
    official_price_id: str

    @classmethod
    def from_named(cls, args: dict[str, object]) -> OfficialPriceClaim:
        raw = args["trade"]
        trade = raw
        raw = args["price"]
        price = values.parse_decimal(raw)
        raw = args["official_price_id"]
        official_price_id = raw
        return cls(trade=trade, price=price, official_price_id=official_price_id)


@dataclass(frozen=True)
class CurrentOfficialPriceClaim:
    """One admitted `CurrentOfficialPrice` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "CurrentOfficialPrice"

    trade: str
    official_price_id: str

    @classmethod
    def from_named(cls, args: dict[str, object]) -> CurrentOfficialPriceClaim:
        raw = args["trade"]
        trade = raw
        raw = args["official_price_id"]
        official_price_id = raw
        return cls(trade=trade, official_price_id=official_price_id)


@dataclass(frozen=True)
class OfficialPriceSupersedesClaim:
    """One admitted `OfficialPriceSupersedes` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "OfficialPriceSupersedes"

    new_official_price_id: str
    prior_official_price_id: str

    @classmethod
    def from_named(cls, args: dict[str, object]) -> OfficialPriceSupersedesClaim:
        raw = args["new_official_price_id"]
        new_official_price_id = raw
        raw = args["prior_official_price_id"]
        prior_official_price_id = raw
        return cls(new_official_price_id=new_official_price_id, prior_official_price_id=prior_official_price_id)


@dataclass(frozen=True)
class TradeSettledClaim:
    """One admitted `TradeSettled` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "TradeSettled"

    trade: str
    settled_qty: Decimal
    settlement_id: str
    official_price_id: str
    effective_on: date

    @classmethod
    def from_named(cls, args: dict[str, object]) -> TradeSettledClaim:
        raw = args["trade"]
        trade = raw
        raw = args["settled_qty"]
        settled_qty = values.parse_decimal(raw)
        raw = args["settlement_id"]
        settlement_id = raw
        raw = args["official_price_id"]
        official_price_id = raw
        raw = args["effective_on"]
        effective_on = values.parse_date(raw)
        return cls(trade=trade, settled_qty=settled_qty, settlement_id=settlement_id, official_price_id=official_price_id, effective_on=effective_on)


@dataclass(frozen=True)
class PositionLimitClaim:
    """One admitted `PositionLimit` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "PositionLimit"

    commodity: str
    limit: Decimal

    @classmethod
    def from_named(cls, args: dict[str, object]) -> PositionLimitClaim:
        raw = args["commodity"]
        commodity = raw
        raw = args["limit"]
        limit = values.parse_decimal(raw)
        return cls(commodity=commodity, limit=limit)


@dataclass(frozen=True)
class SettledUnderTermsClaim:
    """One admitted `SettledUnderTerms` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "SettledUnderTerms"

    settlement_id: str
    version_id: str

    @classmethod
    def from_named(cls, args: dict[str, object]) -> SettledUnderTermsClaim:
        raw = args["settlement_id"]
        settlement_id = raw
        raw = args["version_id"]
        version_id = raw
        return cls(settlement_id=settlement_id, version_id=version_id)


@dataclass(frozen=True)
class TermsTimelineClaim:
    """One admitted `TermsTimeline` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "TermsTimeline"

    trade: str
    version_id: str
    delivery_period: str
    effective_from: date
    quantity: Decimal

    @classmethod
    def from_named(cls, args: dict[str, object]) -> TermsTimelineClaim:
        raw = args["trade"]
        trade = raw
        raw = args["version_id"]
        version_id = raw
        raw = args["delivery_period"]
        delivery_period = raw
        raw = args["effective_from"]
        effective_from = values.parse_date(raw)
        raw = args["quantity"]
        quantity = values.parse_decimal(raw)
        return cls(trade=trade, version_id=version_id, delivery_period=delivery_period, effective_from=effective_from, quantity=quantity)


@dataclass(frozen=True)
class TradeCapturedAdmittedPayload:
    """Payload of an emitted `TradeCapturedAdmitted` intent."""

    INTENT: ClassVar[str] = "TradeCapturedAdmitted"
    _ARG_ORDER: ClassVar[tuple] = ("trade",)

    trade: str

    @classmethod
    def from_args(cls, args: list[object]) -> TradeCapturedAdmittedPayload:
        """Build from the decoded positional values of an outbox
        row's `arguments` (the adapter decodes; this names)."""
        if len(args) != 1:
            raise ValueError(
                f"TradeCapturedAdmitted: payload arity {len(args)} != contract arity 1 "
                f"(schema/payload skew)"
            )
        return cls(*args)


@dataclass(frozen=True)
class TradeTermsAmendedPayload:
    """Payload of an emitted `TradeTermsAmended` intent."""

    INTENT: ClassVar[str] = "TradeTermsAmended"
    _ARG_ORDER: ClassVar[tuple] = ("trade", "new_version_id", "prior_version_id",)

    trade: str
    new_version_id: str
    prior_version_id: str

    @classmethod
    def from_args(cls, args: list[object]) -> TradeTermsAmendedPayload:
        """Build from the decoded positional values of an outbox
        row's `arguments` (the adapter decodes; this names)."""
        if len(args) != 3:
            raise ValueError(
                f"TradeTermsAmended: payload arity {len(args)} != contract arity 3 "
                f"(schema/payload skew)"
            )
        return cls(*args)


@dataclass(frozen=True)
class ConfirmAuthorityGrantedPayload:
    """Payload of an emitted `ConfirmAuthorityGranted` intent."""

    INTENT: ClassVar[str] = "ConfirmAuthorityGranted"
    _ARG_ORDER: ClassVar[tuple] = ("principal", "commodity",)

    principal: str
    commodity: str

    @classmethod
    def from_args(cls, args: list[object]) -> ConfirmAuthorityGrantedPayload:
        """Build from the decoded positional values of an outbox
        row's `arguments` (the adapter decodes; this names)."""
        if len(args) != 2:
            raise ValueError(
                f"ConfirmAuthorityGranted: payload arity {len(args)} != contract arity 2 "
                f"(schema/payload skew)"
            )
        return cls(*args)


@dataclass(frozen=True)
class TradeConfirmedAdmittedPayload:
    """Payload of an emitted `TradeConfirmedAdmitted` intent."""

    INTENT: ClassVar[str] = "TradeConfirmedAdmitted"
    _ARG_ORDER: ClassVar[tuple] = ("trade", "confirmation_id", "official_price_id",)

    trade: str
    confirmation_id: str
    official_price_id: str

    @classmethod
    def from_args(cls, args: list[object]) -> TradeConfirmedAdmittedPayload:
        """Build from the decoded positional values of an outbox
        row's `arguments` (the adapter decodes; this names)."""
        if len(args) != 3:
            raise ValueError(
                f"TradeConfirmedAdmitted: payload arity {len(args)} != contract arity 3 "
                f"(schema/payload skew)"
            )
        return cls(*args)


@dataclass(frozen=True)
class OfficialPriceCorrectedPayload:
    """Payload of an emitted `OfficialPriceCorrected` intent."""

    INTENT: ClassVar[str] = "OfficialPriceCorrected"
    _ARG_ORDER: ClassVar[tuple] = ("trade", "new_official_price_id", "prior_official_price_id",)

    trade: str
    new_official_price_id: str
    prior_official_price_id: str

    @classmethod
    def from_args(cls, args: list[object]) -> OfficialPriceCorrectedPayload:
        """Build from the decoded positional values of an outbox
        row's `arguments` (the adapter decodes; this names)."""
        if len(args) != 3:
            raise ValueError(
                f"OfficialPriceCorrected: payload arity {len(args)} != contract arity 3 "
                f"(schema/payload skew)"
            )
        return cls(*args)


@dataclass(frozen=True)
class TradeSettlementRequestedPayload:
    """Payload of an emitted `TradeSettlementRequested` intent."""

    INTENT: ClassVar[str] = "TradeSettlementRequested"
    _ARG_ORDER: ClassVar[tuple] = ("settlement_id", "trade", "settled_qty",)

    settlement_id: str
    trade: str
    settled_qty: Decimal

    @classmethod
    def from_args(cls, args: list[object]) -> TradeSettlementRequestedPayload:
        """Build from the decoded positional values of an outbox
        row's `arguments` (the adapter decodes; this names)."""
        if len(args) != 3:
            raise ValueError(
                f"TradeSettlementRequested: payload arity {len(args)} != contract arity 3 "
                f"(schema/payload skew)"
            )
        return cls(*args)


@dataclass(frozen=True)
class PositionLimitSetPayload:
    """Payload of an emitted `PositionLimitSet` intent."""

    INTENT: ClassVar[str] = "PositionLimitSet"
    _ARG_ORDER: ClassVar[tuple] = ("commodity", "limit",)

    commodity: str
    limit: Decimal

    @classmethod
    def from_args(cls, args: list[object]) -> PositionLimitSetPayload:
        """Build from the decoded positional values of an outbox
        row's `arguments` (the adapter decodes; this names)."""
        if len(args) != 2:
            raise ValueError(
                f"PositionLimitSet: payload arity {len(args)} != contract arity 2 "
                f"(schema/payload skew)"
            )
        return cls(*args)


INTENT_PAYLOADS = {
    "TradeCapturedAdmitted": TradeCapturedAdmittedPayload,
    "TradeTermsAmended": TradeTermsAmendedPayload,
    "ConfirmAuthorityGranted": ConfirmAuthorityGrantedPayload,
    "TradeConfirmedAdmitted": TradeConfirmedAdmittedPayload,
    "OfficialPriceCorrected": OfficialPriceCorrectedPayload,
    "TradeSettlementRequested": TradeSettlementRequestedPayload,
    "PositionLimitSet": PositionLimitSetPayload,
}
