use super::*;
use morpholog_core::{ArgDecl, PredicateDecl};
use morpholog_surface::parse_program;

fn decl(name: &str, args: &[(&str, PredicateArgKind)]) -> PredicateDecl {
    PredicateDecl {
        name: name.into(),
        args: args
            .iter()
            .map(|(n, k)| ArgDecl {
                name: (*n).to_string(),
                kind: k.clone(),
            })
            .collect(),
        disciplines: Vec::new(),
    }
}

fn render_ok(src: &str) -> RenderedViews {
    let program = parse_program(src).expect("fixture parses");
    let validated = program.validated().expect("fixture validates");
    render_views(validated, "morpholog_views", "sha256:testhash").expect("renders")
}

fn refusals(src: &str, schema: &str) -> Vec<ViewRefusal> {
    let program = parse_program(src).expect("fixture parses");
    let validated = program.validated().expect("fixture validates");
    render_views(validated, schema, "sha256:testhash").expect_err("refuses")
}

// ---- snake_case (pinned, acronym-aware) ----

#[test]
fn snake_case_is_acronym_aware() {
    assert_eq!(snake_case("TradeSettled"), "trade_settled");
    assert_eq!(snake_case("PPAContract"), "ppa_contract");
    assert_eq!(snake_case("TradeID"), "trade_id");
    assert_eq!(snake_case("HTTP2Request"), "http2_request");
    assert_eq!(snake_case("VoyageFixture"), "voyage_fixture");
}

// ---- column_sql: one assertion per kind ----

#[test]
fn column_sql_subject_has_no_cast() {
    let c = column_sql(&PredicateArgKind::Subject, 0);
    assert_eq!(c.expr, "arguments -> 0 ->> 'value'");
}

#[test]
fn column_sql_typed_scalars_cast() {
    assert_eq!(
        column_sql(&PredicateArgKind::Decimal, 1).expr,
        "(arguments -> 1 ->> 'value')::numeric"
    );
    assert_eq!(
        column_sql(&PredicateArgKind::Date, 2).expr,
        "(arguments -> 2 ->> 'value')::date"
    );
    assert_eq!(
        column_sql(&PredicateArgKind::Timestamp, 3).expr,
        "(arguments -> 3 ->> 'value')::timestamptz"
    );
    assert_eq!(
        column_sql(&PredicateArgKind::Duration, 4).expr,
        "CASE WHEN (arguments -> 4 ->> 'value') LIKE '-%' \
             THEN -((substring(arguments -> 4 ->> 'value' FROM 2))::interval) \
             ELSE (arguments -> 4 ->> 'value')::interval END"
    );
    assert_eq!(
        column_sql(&PredicateArgKind::Bool, 5).expr,
        "(arguments -> 5 ->> 'value')::boolean"
    );
}

#[test]
fn column_sql_quantity_reaches_amount_and_notes_unit() {
    let c = column_sql(&PredicateArgKind::Quantity("USD".into()), 2);
    assert_eq!(c.expr, "(arguments -> 2 -> 'value' ->> 'amount')::numeric");
    assert!(
        c.kind_comment.contains("amount in USD"),
        "{}",
        c.kind_comment
    );
}

#[test]
fn column_sql_collection_is_value_array_jsonb() {
    assert_eq!(
        column_sql(&PredicateArgKind::Collection, 0).expr,
        "arguments -> 0 -> 'value'"
    );
}

#[test]
fn column_sql_any_is_the_whole_tagged_object() {
    assert_eq!(column_sql(&PredicateArgKind::Any, 7).expr, "arguments -> 7");
}

// ---- render_views: shape, determinism, exclusion ----

const MIXED: &str = "program mixed\n\
        predicate VoyageFixture(voyage: Subject, vessel: Subject, allowed: Duration)\n\
        transformation t(voyage, vessel, allowed):\n    \
            admit VoyageFixture(voyage, vessel, allowed)\n";

#[test]
fn render_emits_atomic_nonupdatable_metadata_first_view() {
    let r = render_ok(MIXED);
    let sql = &r.sql;
    assert_eq!(r.base_view_count, 1);
    assert_eq!(r.derived_view_count, 0);
    // atomic
    assert!(sql.starts_with("-- Generated by"));
    assert!(sql.contains("BEGIN;"));
    assert!(sql.trim_end().ends_with("COMMIT;"));
    // model hash in header
    assert!(sql.contains("-- model hash: sha256:testhash"));
    // non-updatable CTE
    assert!(sql.contains("WITH governed_claims AS ("));
    assert!(sql.contains("WHERE predicate_name = 'VoyageFixture'"));
    // metadata-first, then business fields in declaration order
    let meta_in = sql.find("_morpholog_asserted_in").unwrap();
    let meta_args = sql.find("_morpholog_arguments").unwrap();
    let voyage = sql.find("AS \"voyage\"").unwrap();
    let allowed = sql.find("AS \"allowed\"").unwrap();
    assert!(meta_in < meta_args && meta_args < voyage && voyage < allowed);
    // typed projection (Duration uses the sign-correcting CASE) + comments
    assert!(sql.contains("CASE WHEN (arguments -> 2 ->> 'value') LIKE '-%'"));
    assert!(sql.contains("END AS \"allowed\""));
    assert!(sql.contains("COMMENT ON VIEW \"morpholog_views\".\"voyage_fixture\" IS"));
    assert!(sql.contains("COMMENT ON COLUMN \"morpholog_views\".\"voyage_fixture\".\"allowed\""));
}

#[test]
fn render_is_byte_deterministic() {
    assert_eq!(render_ok(MIXED).sql, render_ok(MIXED).sql);
}

#[test]
fn catalog_carries_hash_and_inventory() {
    let r = render_ok(MIXED);
    assert!(
        r.sql
            .contains("CREATE OR REPLACE VIEW \"morpholog_views\".\"_morpholog_catalog\"")
    );
    assert!(r.sql.contains("'mixed'::text"));
    assert!(r.sql.contains("'sha256:testhash'::text"));
    assert!(r.sql.contains("'VoyageFixture'::text"));
    assert!(r.sql.contains("'voyage_fixture'::text"));
}

#[test]
fn quantity_and_any_and_collection_render() {
    let src = "program kinds\n\
            predicate K(id: Subject, daily: Decimal[USD], tags: Collection, blob: Any)\n\
            transformation t(id, daily, tags, blob):\n    \
                admit K(id, daily, tags, blob)\n";
    let sql = render_ok(src).sql;
    assert!(sql.contains("(arguments -> 1 -> 'value' ->> 'amount')::numeric AS \"daily\""));
    assert!(sql.contains("arguments -> 2 -> 'value'"));
    assert!(sql.contains("arguments -> 3"));
    assert!(sql.contains("amount in USD"));
}

#[test]
fn derived_heads_get_a_derived_view_over_the_cache() {
    // TermsTimeline is both a predicate and a derived block: its view reads
    // the read cache (filtered by predicate and model hash), while base
    // predicates read morpholog.claims.
    let program = morpholog_examples::trade_lifecycle::program();
    let validated = program.validated().expect("validates");
    let r = render_views(validated, "morpholog_views", "sha256:x").expect("renders");
    assert!(r.base_view_count >= 1 && r.derived_view_count >= 1);
    assert!(
        r.sql
            .contains("CREATE OR REPLACE VIEW \"morpholog_views\".\"trade_settled\""),
        "base view over claims"
    );
    assert!(
        r.sql
            .contains("CREATE OR REPLACE VIEW \"morpholog_views\".\"terms_timeline\""),
        "derived view present"
    );
    assert!(r.sql.contains("FROM morpholog_read.derived_claims c"));
    assert!(r.sql.contains("WHERE c.predicate_name = 'TermsTimeline'"));
    assert!(
        r.sql.contains("AND r.model_hash = 'sha256:x'"),
        "derived view filters by the generated model hash"
    );
    assert!(r.sql.contains("'derived'"), "catalogue marks the kind");
}

#[test]
fn zero_predicates_is_lawful_empty() {
    // A programme with no claim shapes is lawful-empty, not a refusal:
    // a typed-empty catalogue, no views.
    let sql = render("empty", "morpholog_views", "sha256:testhash", &[], &[]);
    assert!(sql.contains("-- no predicates"));
    assert!(sql.contains("NULL::text AS programme_name"));
    assert!(sql.contains("WHERE false;"));
    assert!(sql.contains("BEGIN;") && sql.trim_end().ends_with("COMMIT;"));
}

// ---- refusals ----

#[test]
fn reserved_keyword_field_is_quoted_not_refused() {
    // A reserved-word field (`select`) is allowed: it is double-quoted
    // in the view, so the DDL is valid and consumers quote it in turn.
    let src = "program kw\n\
            predicate P(id: Subject, select: Decimal)\n\
            transformation t(id, select):\n    admit P(id, select)\n";
    let sql = render_ok(src).sql;
    assert!(
        sql.contains("AS \"select\""),
        "reserved-word column should be quoted, not refused: {sql}"
    );
}

#[test]
fn morpholog_prefixed_field_is_refused() {
    // The grammar may not allow a leading-underscore field, so exercise the
    // sweep directly.
    let p = decl(
        "P",
        &[
            ("id", PredicateArgKind::Subject),
            ("_morpholog_x", PredicateArgKind::Decimal),
        ],
    );
    let found = sweep("morpholog_views", &[&p], &[]);
    assert!(found.iter().any(|r| matches!(
        r,
        ViewRefusal::ReservedPrefix { name, .. } if name == "_morpholog_x"
    )));
}

#[test]
fn over_long_identifier_is_refused() {
    let long = "a".repeat(64);
    let p = decl("P", &[(long.as_str(), PredicateArgKind::Decimal)]);
    let found = sweep("morpholog_views", &[&p], &[]);
    assert!(
        found
            .iter()
            .any(|r| matches!(r, ViewRefusal::IdentifierTooLong { .. }))
    );
}

#[test]
fn colliding_view_names_are_refused_naming_both() {
    // `TradeID` and `Trade_id` both snake to `trade_id`.
    let src = "program coll\n\
            predicate TradeID(id: Subject)\n\
            predicate Trade_id(id: Subject)\n\
            transformation t(id):\n    admit TradeID(id)\n";
    let found = refusals(src, "morpholog_views");
    assert!(found.iter().any(|r| matches!(
        r,
        ViewRefusal::ViewNameCollision { generated, .. } if generated == "trade_id"
    )));
}

#[test]
fn a_base_and_derived_view_name_collision_is_refused() {
    // A base predicate and a derived head collide too: `TradeID` (base)
    // and `TradeId` (derived head) both snake to `trade_id`.
    let src = "program mixcoll\n\
            predicate TradeID(id: Subject)\n\
            predicate TradeId(id: Subject, n: Decimal)\n\
            transformation t(id):\n    admit TradeID(id)\n\
            derived TradeId(id):\n    over TradeID(id)\n    value n = sum(1 | TradeID(id))\n";
    let found = refusals(src, "morpholog_views");
    assert!(
        found.iter().any(|r| matches!(
            r,
            ViewRefusal::ViewNameCollision { generated, sources }
                if generated == "trade_id" && sources.len() == 2
        )),
        "a base/derived view-name collision must be refused: {found:?}"
    );
}

#[test]
fn invalid_schema_is_refused() {
    let found = refusals(MIXED, "Bad Schema!");
    assert!(
        found
            .iter()
            .any(|r| matches!(r, ViewRefusal::InvalidSchema { .. }))
    );
}

#[test]
fn refusal_renders_nothing() {
    // A refusal returns Err - there is no String to leak.
    let found = refusals(MIXED, "0bad");
    assert!(!found.is_empty());
}

#[test]
fn keyword_view_names_are_quoted_not_refused() {
    // A predicate named `Order` or `User` snakes to a reserved word;
    // the generated view is quoted rather than refused.
    let src = "program kwviews\n\
            predicate Order(id: Subject)\n\
            predicate User(id: Subject)\n\
            transformation t(id):\n    admit Order(id)\n";
    let sql = render_ok(src).sql;
    assert!(
        sql.contains("\"morpholog_views\".\"order\""),
        "reserved-word view name should be quoted: {sql}"
    );
    assert!(
        sql.contains("\"morpholog_views\".\"user\""),
        "reserved-word view name should be quoted: {sql}"
    );
}

#[test]
fn morpholog_prefixed_view_name_is_refused() {
    // A name snaking into the `_morpholog_` namespace could collide with
    // `_morpholog_catalog`. Exercised via the sweep, since the grammar may
    // not allow the name.
    let p = decl("_morphologThing", &[("id", PredicateArgKind::Subject)]);
    let found = sweep("morpholog_views", &[&p], &[]);
    assert!(found.iter().any(|r| matches!(
        r,
        ViewRefusal::ReservedPrefix { name, .. } if name == "_morpholog_thing"
    )));
}

#[test]
fn header_values_cannot_break_out_of_the_comment() {
    // The public API accepts any programme name and hash; a newline must
    // not escape the `--` header comment and inject SQL.
    let sql = render(
        "evil\nDROP TABLE x;",
        "morpholog_views",
        "sha256:a\nb",
        &[],
        &[],
    );
    assert!(
        !sql.contains("\nDROP TABLE x;"),
        "a newline escaped the header comment: {sql}"
    );
    assert!(sql.contains("evil\\nDROP TABLE x;"));
    assert!(sql.contains("sha256:a\\nb"));
}
